### ISSUE TITLE
What is inside "Flint" folder?

### ISSUE THREAD

**Issue by izgzhen** [s92025592025/CSE403-Wi19-Flint#9]
And, is it in a testable state?

Meta-NOTE: it doens't have to be a minimum viable product to be compiled and tried. So just give a hint on how to run you code and what am I running :)

**Comment by izgzhen** [comment]
I would expect to see them in either `README.md` or `Manual.md`

**Comment by izgzhen** [comment]
It is generally weird to have a collaborative project with empty documentation files

**Comment by s92025592025** [comment]
We have the draft in another place :)
